//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm.event;

import aero.aixm.AbstractAIXMPropertyType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ASHTAMPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ASHTAMPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1/event}ASHTAM"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ASHTAMPropertyType", propOrder = {
    "ashtam"
})
public class ASHTAMPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "ASHTAM", required = true)
    protected ASHTAMType ashtam;

    /**
     * Gets the value of the ashtam property.
     * 
     * @return
     *     possible object is
     *     {@link ASHTAMType }
     *     
     */
    public ASHTAMType getASHTAM() {
        return ashtam;
    }

    /**
     * Sets the value of the ashtam property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASHTAMType }
     *     
     */
    public void setASHTAM(ASHTAMType value) {
        this.ashtam = value;
    }

    public boolean isSetASHTAM() {
        return (this.ashtam!= null);
    }

}
