//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm.event;

import java.util.ArrayList;
import java.util.List;
import aero.aixm.AbstractAIXMTimeSliceType;
import aero.aixm.AbstractExtensionType;
import aero.aixm.AirportHeliportPropertyType;
import aero.aixm.AirspacePropertyType;
import aero.aixm.ContactInformationPropertyType;
import aero.aixm.DateTimeType;
import aero.aixm.NotePropertyType;
import aero.aixm.TextDesignatorType;
import aero.aixm.TextNameType;
import aero.aixm.TextRemarkType;
import aero.aixm.UnitPropertyType;
import aero.aixm.XHTMLType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventTimeSliceType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="EventTimeSliceType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMTimeSliceType">
 *       <sequence>
 *         <group ref="{http://www.aixm.aero/schema/5.1.1/event}EventPropertyGroup"/>
 *         <element name="extension" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element ref="{http://www.aixm.aero/schema/5.1.1/event}AbstractEventExtension"/>
 *                 </sequence>
 *                 <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventTimeSliceType", propOrder = {
    "eventName",
    "designator",
    "scenario",
    "version",
    "estimatedValidity",
    "activity",
    "summary",
    "concernedAirspace",
    "concernedAirportHeliport",
    "parentEvent",
    "contactInformation",
    "causeEvent",
    "container",
    "notification",
    "provider",
    "annotation",
    "extension"
})
public class EventTimeSliceType
    extends AbstractAIXMTimeSliceType
{

    /**
     * A title by which the event is known to people involved in aeronautical operations
     * 
     */
    @XmlElementRef(name = "name", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<TextNameType> eventName;
    /**
     * A code by which the event is identified in applications and systems used in aeronautical operation
     * 
     */
    @XmlElementRef(name = "designator", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<TextDesignatorType> designator;
    /**
     * The identifier of a predefined scenario that provides the data encoding rules for a specific operational situation
     * 
     */
    @XmlElementRef(name = "scenario", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<TextDesignatorType> scenario;
    /**
     * The version of the predefined coding scenario (usually the version of the document that contains the scenario)
     * 
     */
    @XmlElementRef(name = "version", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<TextDesignatorType> version;
    /**
     * For Events that have an indeterminate end of life, it indicates a date and time by which the event is expected to end
     *                         
     *                         Note: <i>if this estimated end of validity is reached without any other update of the Event data, the Event is considered to be still valid.</i>
     * 
     */
    @XmlElementRef(name = "estimatedValidity", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<DateTimeType> estimatedValidity;
    /**
     * A short indication of the type of activity or operational situation that makes the event
     * 
     */
    @XmlElementRef(name = "activity", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<TextRemarkType> activity;
    /**
     * A description of the event, with the possibility to include maps, diagrams and formatted text
     * 
     */
    @XmlElementRef(name = "summary", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<XHTMLType> summary;
    @XmlElement(nillable = true)
    protected List<AirspacePropertyType> concernedAirspace;
    @XmlElement(nillable = true)
    protected List<AirportHeliportPropertyType> concernedAirportHeliport;
    /**
     * Identifies another Event as being the owner of the current event, which allows organising large events into smaller sub-events.
     * 
     */
    @XmlElementRef(name = "parentEvent", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<EventPropertyType> parentEvent;
    @XmlElementRef(name = "contactInformation", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<ContactInformationPropertyType> contactInformation;
    /**
     * Identifies another Event as being a direct cause of the current Event.
     * 
     */
    @XmlElementRef(name = "causeEvent", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<EventPropertyType> causeEvent;
    @XmlElement(nillable = true)
    protected List<AISProductPropertyType> container;
    @XmlElement(nillable = true)
    protected List<AISMessagePropertyType> notification;
    @XmlElementRef(name = "provider", namespace = "http://www.aixm.aero/schema/5.1.1/event", type = JAXBElement.class, required = false)
    protected JAXBElement<UnitPropertyType> provider;
    @XmlElement(nillable = true)
    protected List<NotePropertyType> annotation;
    protected List<EventTimeSliceType.Extension> extension;

    /**
     * A title by which the event is known to people involved in aeronautical operations
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextNameType }{@code >}
     *     
     */
    public JAXBElement<TextNameType> getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextNameType }{@code >}
     *     
     * @see #getEventName()
     */
    public void setEventName(JAXBElement<TextNameType> value) {
        this.eventName = value;
    }

    public boolean isSetEventName() {
        return (this.eventName!= null);
    }

    /**
     * A code by which the event is identified in applications and systems used in aeronautical operation
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextDesignatorType }{@code >}
     *     
     */
    public JAXBElement<TextDesignatorType> getDesignator() {
        return designator;
    }

    /**
     * Sets the value of the designator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextDesignatorType }{@code >}
     *     
     * @see #getDesignator()
     */
    public void setDesignator(JAXBElement<TextDesignatorType> value) {
        this.designator = value;
    }

    public boolean isSetDesignator() {
        return (this.designator!= null);
    }

    /**
     * The identifier of a predefined scenario that provides the data encoding rules for a specific operational situation
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextDesignatorType }{@code >}
     *     
     */
    public JAXBElement<TextDesignatorType> getScenario() {
        return scenario;
    }

    /**
     * Sets the value of the scenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextDesignatorType }{@code >}
     *     
     * @see #getScenario()
     */
    public void setScenario(JAXBElement<TextDesignatorType> value) {
        this.scenario = value;
    }

    public boolean isSetScenario() {
        return (this.scenario!= null);
    }

    /**
     * The version of the predefined coding scenario (usually the version of the document that contains the scenario)
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextDesignatorType }{@code >}
     *     
     */
    public JAXBElement<TextDesignatorType> getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextDesignatorType }{@code >}
     *     
     * @see #getVersion()
     */
    public void setVersion(JAXBElement<TextDesignatorType> value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    /**
     * For Events that have an indeterminate end of life, it indicates a date and time by which the event is expected to end
     *                         
     *                         Note: <i>if this estimated end of validity is reached without any other update of the Event data, the Event is considered to be still valid.</i>
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     *     
     */
    public JAXBElement<DateTimeType> getEstimatedValidity() {
        return estimatedValidity;
    }

    /**
     * Sets the value of the estimatedValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     *     
     * @see #getEstimatedValidity()
     */
    public void setEstimatedValidity(JAXBElement<DateTimeType> value) {
        this.estimatedValidity = value;
    }

    public boolean isSetEstimatedValidity() {
        return (this.estimatedValidity!= null);
    }

    /**
     * A short indication of the type of activity or operational situation that makes the event
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextRemarkType }{@code >}
     *     
     */
    public JAXBElement<TextRemarkType> getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextRemarkType }{@code >}
     *     
     * @see #getActivity()
     */
    public void setActivity(JAXBElement<TextRemarkType> value) {
        this.activity = value;
    }

    public boolean isSetActivity() {
        return (this.activity!= null);
    }

    /**
     * A description of the event, with the possibility to include maps, diagrams and formatted text
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XHTMLType }{@code >}
     *     
     */
    public JAXBElement<XHTMLType> getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XHTMLType }{@code >}
     *     
     * @see #getSummary()
     */
    public void setSummary(JAXBElement<XHTMLType> value) {
        this.summary = value;
    }

    public boolean isSetSummary() {
        return (this.summary!= null);
    }

    /**
     * Gets the value of the concernedAirspace property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the concernedAirspace property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getConcernedAirspace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirspacePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the concernedAirspace property.
     */
    public List<AirspacePropertyType> getConcernedAirspace() {
        if (concernedAirspace == null) {
            concernedAirspace = new ArrayList<>();
        }
        return this.concernedAirspace;
    }

    public boolean isSetConcernedAirspace() {
        return ((this.concernedAirspace!= null)&&(!this.concernedAirspace.isEmpty()));
    }

    public void unsetConcernedAirspace() {
        this.concernedAirspace = null;
    }

    /**
     * Gets the value of the concernedAirportHeliport property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the concernedAirportHeliport property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getConcernedAirportHeliport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirportHeliportPropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the concernedAirportHeliport property.
     */
    public List<AirportHeliportPropertyType> getConcernedAirportHeliport() {
        if (concernedAirportHeliport == null) {
            concernedAirportHeliport = new ArrayList<>();
        }
        return this.concernedAirportHeliport;
    }

    public boolean isSetConcernedAirportHeliport() {
        return ((this.concernedAirportHeliport!= null)&&(!this.concernedAirportHeliport.isEmpty()));
    }

    public void unsetConcernedAirportHeliport() {
        this.concernedAirportHeliport = null;
    }

    /**
     * Identifies another Event as being the owner of the current event, which allows organising large events into smaller sub-events.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EventPropertyType }{@code >}
     *     
     */
    public JAXBElement<EventPropertyType> getParentEvent() {
        return parentEvent;
    }

    /**
     * Sets the value of the parentEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EventPropertyType }{@code >}
     *     
     * @see #getParentEvent()
     */
    public void setParentEvent(JAXBElement<EventPropertyType> value) {
        this.parentEvent = value;
    }

    public boolean isSetParentEvent() {
        return (this.parentEvent!= null);
    }

    /**
     * Gets the value of the contactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ContactInformationPropertyType }{@code >}
     *     
     */
    public JAXBElement<ContactInformationPropertyType> getContactInformation() {
        return contactInformation;
    }

    /**
     * Sets the value of the contactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ContactInformationPropertyType }{@code >}
     *     
     */
    public void setContactInformation(JAXBElement<ContactInformationPropertyType> value) {
        this.contactInformation = value;
    }

    public boolean isSetContactInformation() {
        return (this.contactInformation!= null);
    }

    /**
     * Identifies another Event as being a direct cause of the current Event.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EventPropertyType }{@code >}
     *     
     */
    public JAXBElement<EventPropertyType> getCauseEvent() {
        return causeEvent;
    }

    /**
     * Sets the value of the causeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EventPropertyType }{@code >}
     *     
     * @see #getCauseEvent()
     */
    public void setCauseEvent(JAXBElement<EventPropertyType> value) {
        this.causeEvent = value;
    }

    public boolean isSetCauseEvent() {
        return (this.causeEvent!= null);
    }

    /**
     * Gets the value of the container property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the container property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getContainer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AISProductPropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the container property.
     */
    public List<AISProductPropertyType> getContainer() {
        if (container == null) {
            container = new ArrayList<>();
        }
        return this.container;
    }

    public boolean isSetContainer() {
        return ((this.container!= null)&&(!this.container.isEmpty()));
    }

    public void unsetContainer() {
        this.container = null;
    }

    /**
     * Gets the value of the notification property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notification property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AISMessagePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the notification property.
     */
    public List<AISMessagePropertyType> getNotification() {
        if (notification == null) {
            notification = new ArrayList<>();
        }
        return this.notification;
    }

    public boolean isSetNotification() {
        return ((this.notification!= null)&&(!this.notification.isEmpty()));
    }

    public void unsetNotification() {
        this.notification = null;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UnitPropertyType }{@code >}
     *     
     */
    public JAXBElement<UnitPropertyType> getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UnitPropertyType }{@code >}
     *     
     */
    public void setProvider(JAXBElement<UnitPropertyType> value) {
        this.provider = value;
    }

    public boolean isSetProvider() {
        return (this.provider!= null);
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the annotation property.
     */
    public List<NotePropertyType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<>();
        }
        return this.annotation;
    }

    public boolean isSetAnnotation() {
        return ((this.annotation!= null)&&(!this.annotation.isEmpty()));
    }

    public void unsetAnnotation() {
        this.annotation = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventTimeSliceType.Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<EventTimeSliceType.Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element ref="{http://www.aixm.aero/schema/5.1.1/event}AbstractEventExtension"/>
     *       </sequence>
     *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractEventExtension"
    })
    public static class Extension {

        @XmlElement(name = "AbstractEventExtension", required = true)
        protected AbstractExtensionType abstractEventExtension;
        @XmlAttribute(name = "owns")
        protected Boolean owns;

        /**
         * Gets the value of the abstractEventExtension property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractExtensionType }
         *     
         */
        public AbstractExtensionType getAbstractEventExtension() {
            return abstractEventExtension;
        }

        /**
         * Sets the value of the abstractEventExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractExtensionType }
         *     
         */
        public void setAbstractEventExtension(AbstractExtensionType value) {
            this.abstractEventExtension = value;
        }

        public boolean isSetAbstractEventExtension() {
            return (this.abstractEventExtension!= null);
        }

        /**
         * Gets the value of the owns property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOwns() {
            if (owns == null) {
                return false;
            } else {
                return owns;
            }
        }

        /**
         * Sets the value of the owns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOwns(boolean value) {
            this.owns = value;
        }

        public boolean isSetOwns() {
            return (this.owns!= null);
        }

        public void unsetOwns() {
            this.owns = null;
        }

    }

}
