//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AirspaceLayerClassPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AirspaceLayerClassPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}AirspaceLayerClass"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirspaceLayerClassPropertyType", propOrder = {
    "airspaceLayerClass"
})
public class AirspaceLayerClassPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "AirspaceLayerClass", required = true)
    protected AirspaceLayerClassType airspaceLayerClass;

    /**
     * Gets the value of the airspaceLayerClass property.
     * 
     * @return
     *     possible object is
     *     {@link AirspaceLayerClassType }
     *     
     */
    public AirspaceLayerClassType getAirspaceLayerClass() {
        return airspaceLayerClass;
    }

    /**
     * Sets the value of the airspaceLayerClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirspaceLayerClassType }
     *     
     */
    public void setAirspaceLayerClass(AirspaceLayerClassType value) {
        this.airspaceLayerClass = value;
    }

    public boolean isSetAirspaceLayerClass() {
        return (this.airspaceLayerClass!= null);
    }

}
