//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthorityForSpecialNavigationSystemPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AuthorityForSpecialNavigationSystemPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}AuthorityForSpecialNavigationSystem"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthorityForSpecialNavigationSystemPropertyType", propOrder = {
    "authorityForSpecialNavigationSystem"
})
public class AuthorityForSpecialNavigationSystemPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "AuthorityForSpecialNavigationSystem", required = true)
    protected AuthorityForSpecialNavigationSystemType authorityForSpecialNavigationSystem;

    /**
     * Gets the value of the authorityForSpecialNavigationSystem property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorityForSpecialNavigationSystemType }
     *     
     */
    public AuthorityForSpecialNavigationSystemType getAuthorityForSpecialNavigationSystem() {
        return authorityForSpecialNavigationSystem;
    }

    /**
     * Sets the value of the authorityForSpecialNavigationSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorityForSpecialNavigationSystemType }
     *     
     */
    public void setAuthorityForSpecialNavigationSystem(AuthorityForSpecialNavigationSystemType value) {
        this.authorityForSpecialNavigationSystem = value;
    }

    public boolean isSetAuthorityForSpecialNavigationSystem() {
        return (this.authorityForSpecialNavigationSystem!= null);
    }

}
