//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FASDataBlockPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FASDataBlockPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}FASDataBlock"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FASDataBlockPropertyType", propOrder = {
    "fasDataBlock"
})
public class FASDataBlockPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "FASDataBlock", required = true)
    protected FASDataBlockType fasDataBlock;

    /**
     * Gets the value of the fasDataBlock property.
     * 
     * @return
     *     possible object is
     *     {@link FASDataBlockType }
     *     
     */
    public FASDataBlockType getFASDataBlock() {
        return fasDataBlock;
    }

    /**
     * Sets the value of the fasDataBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link FASDataBlockType }
     *     
     */
    public void setFASDataBlock(FASDataBlockType value) {
        this.fasDataBlock = value;
    }

    public boolean isSetFASDataBlock() {
        return (this.fasDataBlock!= null);
    }

}
