//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightRestrictionRoutePropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FlightRestrictionRoutePropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}FlightRestrictionRoute"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightRestrictionRoutePropertyType", propOrder = {
    "flightRestrictionRoute"
})
public class FlightRestrictionRoutePropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "FlightRestrictionRoute", required = true)
    protected FlightRestrictionRouteType flightRestrictionRoute;

    /**
     * Gets the value of the flightRestrictionRoute property.
     * 
     * @return
     *     possible object is
     *     {@link FlightRestrictionRouteType }
     *     
     */
    public FlightRestrictionRouteType getFlightRestrictionRoute() {
        return flightRestrictionRoute;
    }

    /**
     * Sets the value of the flightRestrictionRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightRestrictionRouteType }
     *     
     */
    public void setFlightRestrictionRoute(FlightRestrictionRouteType value) {
        this.flightRestrictionRoute = value;
    }

    public boolean isSetFlightRestrictionRoute() {
        return (this.flightRestrictionRoute!= null);
    }

}
