//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeteorologyPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MeteorologyPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}Meteorology"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteorologyPropertyType", propOrder = {
    "meteorology"
})
public class MeteorologyPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "Meteorology", required = true)
    protected MeteorologyType meteorology;

    /**
     * Gets the value of the meteorology property.
     * 
     * @return
     *     possible object is
     *     {@link MeteorologyType }
     *     
     */
    public MeteorologyType getMeteorology() {
        return meteorology;
    }

    /**
     * Sets the value of the meteorology property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeteorologyType }
     *     
     */
    public void setMeteorology(MeteorologyType value) {
        this.meteorology = value;
    }

    public boolean isSetMeteorology() {
        return (this.meteorology!= null);
    }

}
