//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MissedApproachGroupPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MissedApproachGroupPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}MissedApproachGroup"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MissedApproachGroupPropertyType", propOrder = {
    "missedApproachGroup"
})
public class MissedApproachGroupPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "MissedApproachGroup", required = true)
    protected MissedApproachGroupType missedApproachGroup;

    /**
     * Gets the value of the missedApproachGroup property.
     * 
     * @return
     *     possible object is
     *     {@link MissedApproachGroupType }
     *     
     */
    public MissedApproachGroupType getMissedApproachGroup() {
        return missedApproachGroup;
    }

    /**
     * Sets the value of the missedApproachGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MissedApproachGroupType }
     *     
     */
    public void setMissedApproachGroup(MissedApproachGroupType value) {
        this.missedApproachGroup = value;
    }

    public boolean isSetMissedApproachGroup() {
        return (this.missedApproachGroup!= null);
    }

}
