//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObstacleAssessmentAreaPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ObstacleAssessmentAreaPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}ObstacleAssessmentArea"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObstacleAssessmentAreaPropertyType", propOrder = {
    "obstacleAssessmentArea"
})
public class ObstacleAssessmentAreaPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "ObstacleAssessmentArea", required = true)
    protected ObstacleAssessmentAreaType obstacleAssessmentArea;

    /**
     * Gets the value of the obstacleAssessmentArea property.
     * 
     * @return
     *     possible object is
     *     {@link ObstacleAssessmentAreaType }
     *     
     */
    public ObstacleAssessmentAreaType getObstacleAssessmentArea() {
        return obstacleAssessmentArea;
    }

    /**
     * Sets the value of the obstacleAssessmentArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObstacleAssessmentAreaType }
     *     
     */
    public void setObstacleAssessmentArea(ObstacleAssessmentAreaType value) {
        this.obstacleAssessmentArea = value;
    }

    public boolean isSetObstacleAssessmentArea() {
        return (this.obstacleAssessmentArea!= null);
    }

}
