//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import java.util.ArrayList;
import java.util.List;
import aero.aixm.event.PilotControlledLightingExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PilotControlledLightingTimeSliceType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PilotControlledLightingTimeSliceType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMTimeSliceType">
 *       <sequence>
 *         <group ref="{http://www.aixm.aero/schema/5.1.1}PilotControlledLightingPropertyGroup"/>
 *         <element name="extension" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractPilotControlledLightingExtension"/>
 *                 </sequence>
 *                 <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PilotControlledLightingTimeSliceType", propOrder = {
    "type",
    "duration",
    "intensitySteps",
    "standByIntensity",
    "radioFrequency",
    "activationInstruction",
    "controlledLightIntensity",
    "activatedGroundLighting",
    "annotation",
    "extension"
})
public class PilotControlledLightingTimeSliceType
    extends AbstractAIXMTimeSliceType
{

    @XmlElementRef(name = "type", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodePilotControlledLightingType> type;
    @XmlElementRef(name = "duration", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class, required = false)
    protected JAXBElement<ValDurationType> duration;
    @XmlElementRef(name = "intensitySteps", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class, required = false)
    protected JAXBElement<NoNumberType> intensitySteps;
    @XmlElementRef(name = "standByIntensity", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class, required = false)
    protected JAXBElement<CodeIntensityStandByType> standByIntensity;
    @XmlElementRef(name = "radioFrequency", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class, required = false)
    protected JAXBElement<ValFrequencyType> radioFrequency;
    @XmlElementRef(name = "activationInstruction", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class, required = false)
    protected JAXBElement<TextInstructionType> activationInstruction;
    @XmlElement(nillable = true)
    protected List<LightActivationPropertyType> controlledLightIntensity;
    @XmlElement(nillable = true)
    protected List<GroundLightSystemPropertyType> activatedGroundLighting;
    @XmlElement(nillable = true)
    protected List<NotePropertyType> annotation;
    protected List<PilotControlledLightingTimeSliceType.Extension> extension;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodePilotControlledLightingType }{@code >}
     *     
     */
    public JAXBElement<CodePilotControlledLightingType> getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodePilotControlledLightingType }{@code >}
     *     
     */
    public void setType(JAXBElement<CodePilotControlledLightingType> value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValDurationType }{@code >}
     *     
     */
    public JAXBElement<ValDurationType> getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValDurationType }{@code >}
     *     
     */
    public void setDuration(JAXBElement<ValDurationType> value) {
        this.duration = value;
    }

    public boolean isSetDuration() {
        return (this.duration!= null);
    }

    /**
     * Gets the value of the intensitySteps property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NoNumberType }{@code >}
     *     
     */
    public JAXBElement<NoNumberType> getIntensitySteps() {
        return intensitySteps;
    }

    /**
     * Sets the value of the intensitySteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NoNumberType }{@code >}
     *     
     */
    public void setIntensitySteps(JAXBElement<NoNumberType> value) {
        this.intensitySteps = value;
    }

    public boolean isSetIntensitySteps() {
        return (this.intensitySteps!= null);
    }

    /**
     * Gets the value of the standByIntensity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CodeIntensityStandByType }{@code >}
     *     
     */
    public JAXBElement<CodeIntensityStandByType> getStandByIntensity() {
        return standByIntensity;
    }

    /**
     * Sets the value of the standByIntensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CodeIntensityStandByType }{@code >}
     *     
     */
    public void setStandByIntensity(JAXBElement<CodeIntensityStandByType> value) {
        this.standByIntensity = value;
    }

    public boolean isSetStandByIntensity() {
        return (this.standByIntensity!= null);
    }

    /**
     * Gets the value of the radioFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValFrequencyType }{@code >}
     *     
     */
    public JAXBElement<ValFrequencyType> getRadioFrequency() {
        return radioFrequency;
    }

    /**
     * Sets the value of the radioFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValFrequencyType }{@code >}
     *     
     */
    public void setRadioFrequency(JAXBElement<ValFrequencyType> value) {
        this.radioFrequency = value;
    }

    public boolean isSetRadioFrequency() {
        return (this.radioFrequency!= null);
    }

    /**
     * Gets the value of the activationInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TextInstructionType }{@code >}
     *     
     */
    public JAXBElement<TextInstructionType> getActivationInstruction() {
        return activationInstruction;
    }

    /**
     * Sets the value of the activationInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TextInstructionType }{@code >}
     *     
     */
    public void setActivationInstruction(JAXBElement<TextInstructionType> value) {
        this.activationInstruction = value;
    }

    public boolean isSetActivationInstruction() {
        return (this.activationInstruction!= null);
    }

    /**
     * Gets the value of the controlledLightIntensity property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlledLightIntensity property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getControlledLightIntensity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LightActivationPropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the controlledLightIntensity property.
     */
    public List<LightActivationPropertyType> getControlledLightIntensity() {
        if (controlledLightIntensity == null) {
            controlledLightIntensity = new ArrayList<>();
        }
        return this.controlledLightIntensity;
    }

    public boolean isSetControlledLightIntensity() {
        return ((this.controlledLightIntensity!= null)&&(!this.controlledLightIntensity.isEmpty()));
    }

    public void unsetControlledLightIntensity() {
        this.controlledLightIntensity = null;
    }

    /**
     * Gets the value of the activatedGroundLighting property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activatedGroundLighting property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getActivatedGroundLighting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroundLightSystemPropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the activatedGroundLighting property.
     */
    public List<GroundLightSystemPropertyType> getActivatedGroundLighting() {
        if (activatedGroundLighting == null) {
            activatedGroundLighting = new ArrayList<>();
        }
        return this.activatedGroundLighting;
    }

    public boolean isSetActivatedGroundLighting() {
        return ((this.activatedGroundLighting!= null)&&(!this.activatedGroundLighting.isEmpty()));
    }

    public void unsetActivatedGroundLighting() {
        this.activatedGroundLighting = null;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the annotation property.
     */
    public List<NotePropertyType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<>();
        }
        return this.annotation;
    }

    public boolean isSetAnnotation() {
        return ((this.annotation!= null)&&(!this.annotation.isEmpty()));
    }

    public void unsetAnnotation() {
        this.annotation = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PilotControlledLightingTimeSliceType.Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<PilotControlledLightingTimeSliceType.Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractPilotControlledLightingExtension"/>
     *       </sequence>
     *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractPilotControlledLightingExtension"
    })
    public static class Extension {

        @XmlElementRef(name = "AbstractPilotControlledLightingExtension", namespace = "http://www.aixm.aero/schema/5.1.1", type = JAXBElement.class)
        protected JAXBElement<? extends AbstractExtensionType> abstractPilotControlledLightingExtension;
        @XmlAttribute(name = "owns")
        protected Boolean owns;

        /**
         * Gets the value of the abstractPilotControlledLightingExtension property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link AbstractExtensionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PilotControlledLightingExtensionType }{@code >}
         *     
         */
        public JAXBElement<? extends AbstractExtensionType> getAbstractPilotControlledLightingExtension() {
            return abstractPilotControlledLightingExtension;
        }

        /**
         * Sets the value of the abstractPilotControlledLightingExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link AbstractExtensionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PilotControlledLightingExtensionType }{@code >}
         *     
         */
        public void setAbstractPilotControlledLightingExtension(JAXBElement<? extends AbstractExtensionType> value) {
            this.abstractPilotControlledLightingExtension = value;
        }

        public boolean isSetAbstractPilotControlledLightingExtension() {
            return (this.abstractPilotControlledLightingExtension!= null);
        }

        /**
         * Gets the value of the owns property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOwns() {
            if (owns == null) {
                return false;
            } else {
                return owns;
            }
        }

        /**
         * Sets the value of the owns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOwns(boolean value) {
            this.owns = value;
        }

        public boolean isSetOwns() {
            return (this.owns!= null);
        }

        public void unsetOwns() {
            this.owns = null;
        }

    }

}
