//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RadioCommunicationOperationalStatusPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="RadioCommunicationOperationalStatusPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}RadioCommunicationOperationalStatus"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioCommunicationOperationalStatusPropertyType", propOrder = {
    "radioCommunicationOperationalStatus"
})
public class RadioCommunicationOperationalStatusPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "RadioCommunicationOperationalStatus", required = true)
    protected RadioCommunicationOperationalStatusType radioCommunicationOperationalStatus;

    /**
     * Gets the value of the radioCommunicationOperationalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RadioCommunicationOperationalStatusType }
     *     
     */
    public RadioCommunicationOperationalStatusType getRadioCommunicationOperationalStatus() {
        return radioCommunicationOperationalStatus;
    }

    /**
     * Sets the value of the radioCommunicationOperationalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioCommunicationOperationalStatusType }
     *     
     */
    public void setRadioCommunicationOperationalStatus(RadioCommunicationOperationalStatusType value) {
        this.radioCommunicationOperationalStatus = value;
    }

    public boolean isSetRadioCommunicationOperationalStatus() {
        return (this.radioCommunicationOperationalStatus!= null);
    }

}
