//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxiwayMarkingTimeSlicePropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TaxiwayMarkingTimeSlicePropertyType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}TaxiwayMarkingTimeSlice"/>
 *       </sequence>
 *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxiwayMarkingTimeSlicePropertyType", propOrder = {
    "taxiwayMarkingTimeSlice"
})
public class TaxiwayMarkingTimeSlicePropertyType {

    @XmlElement(name = "TaxiwayMarkingTimeSlice", required = true)
    protected TaxiwayMarkingTimeSliceType taxiwayMarkingTimeSlice;
    @XmlAttribute(name = "owns")
    protected Boolean owns;

    /**
     * Gets the value of the taxiwayMarkingTimeSlice property.
     * 
     * @return
     *     possible object is
     *     {@link TaxiwayMarkingTimeSliceType }
     *     
     */
    public TaxiwayMarkingTimeSliceType getTaxiwayMarkingTimeSlice() {
        return taxiwayMarkingTimeSlice;
    }

    /**
     * Sets the value of the taxiwayMarkingTimeSlice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxiwayMarkingTimeSliceType }
     *     
     */
    public void setTaxiwayMarkingTimeSlice(TaxiwayMarkingTimeSliceType value) {
        this.taxiwayMarkingTimeSlice = value;
    }

    public boolean isSetTaxiwayMarkingTimeSlice() {
        return (this.taxiwayMarkingTimeSlice!= null);
    }

    /**
     * Gets the value of the owns property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOwns() {
        if (owns == null) {
            return false;
        } else {
            return owns;
        }
    }

    /**
     * Sets the value of the owns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwns(boolean value) {
        this.owns = value;
    }

    public boolean isSetOwns() {
        return (this.owns!= null);
    }

    public void unsetOwns() {
        this.owns = null;
    }

}
