//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerticalStructurePartPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="VerticalStructurePartPropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element ref="{http://www.aixm.aero/schema/5.1.1}VerticalStructurePart"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalStructurePartPropertyType", propOrder = {
    "verticalStructurePart"
})
public class VerticalStructurePartPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "VerticalStructurePart", required = true)
    protected VerticalStructurePartType verticalStructurePart;

    /**
     * Gets the value of the verticalStructurePart property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalStructurePartType }
     *     
     */
    public VerticalStructurePartType getVerticalStructurePart() {
        return verticalStructurePart;
    }

    /**
     * Sets the value of the verticalStructurePart property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalStructurePartType }
     *     
     */
    public void setVerticalStructurePart(VerticalStructurePartType value) {
        this.verticalStructurePart = value;
    }

    public boolean isSetVerticalStructurePart() {
        return (this.verticalStructurePart!= null);
    }

}
